/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DayItem = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'order' : IDL.Nat,
  'tagline' : IDL.Text,
  'days' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'exclusions' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'nights' : IDL.Nat,
  'price' : IDL.Nat,
  'itinerary' : IDL.Vec(DayItem),
  'priceLabel' : IDL.Text,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'packageName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'packageId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func([Package], [IDL.Nat], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'getAllActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPackageById' : IDL.Func([IDL.Nat], [Package], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderPackages' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnquiry' : IDL.Func([Enquiry], [IDL.Nat], []),
  'togglePackageActiveStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updatePackage' : IDL.Func([IDL.Nat, Package], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DayItem = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'order' : IDL.Nat,
    'tagline' : IDL.Text,
    'days' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'exclusions' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'nights' : IDL.Nat,
    'price' : IDL.Nat,
    'itinerary' : IDL.Vec(DayItem),
    'priceLabel' : IDL.Text,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'packageName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'packageId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func([Package], [IDL.Nat], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'getAllActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPackageById' : IDL.Func([IDL.Nat], [Package], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderPackages' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnquiry' : IDL.Func([Enquiry], [IDL.Nat], []),
    'togglePackageActiveStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updatePackage' : IDL.Func([IDL.Nat, Package], [], []),
  });
};

export const init = ({ IDL }) => { return []; };